Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 80
  IgnoredPatterns: ['\A#']

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Enabled: false

Style/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*.rb'
    - 'spec/**/*.rb'
